FROM python:3.11-slim

WORKDIR /app

# Instalación de dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código fuente
COPY ./app ./app

# Exponer el puerto de FastAPI
EXPOSE 8000

# Comando para iniciar la API con Uvicorn
CMD ["uvicorn", "app.application.main:app", "--host", "0.0.0.0", "--port", "8000"]