from __future__ import annotations
from typing import Protocol, Optional
from app.domain.entities import Customer, Account, Transaction, LedgerEntry
from app.domain.enums import TransactionStatus

class CustomerRepository(Protocol):
    def add(self, customer: Customer) -> None: ...
    def get_by_id(self, customer_id: str) -> Optional[Customer]: ...
    def get_by_email(self, email: str) -> Optional[Customer]: ...
    def list(self) -> list[Customer]: ...

class AccountRepository(Protocol):
    def add(self, account: Account) -> None: ...
    def get_by_id(self, account_id: str) -> Optional[Account]: ...
    def list_by_customer(self, customer_id: str) -> list[Account]: ...
    def update(self, account: Account) -> None: ...
    def find_by_currency(self, currency: str) -> list[Account]: ...

class TransactionRepository(Protocol):
    def add(self, transaction: Transaction) -> None: ...
    def get_by_id(self, transaction_id: str) -> Optional[Transaction]: ...
    def update_status(self, transaction_id: str, status: TransactionStatus) -> None: ...
    def list_by_account(self, account_id: str) -> list[Transaction]: ...
    def list_recent(self, account_id: str, minutes: int) -> list[Transaction]: ...

class LedgerRepository(Protocol):
    def add(self, entry: LedgerEntry) -> None: ...
    def list_by_transaction(self, transaction_id: str) -> list[LedgerEntry]: ...